#!/usr/bin/env python3
"""Architecture drift check.

The per-block repos are the SOURCE OF TRUTH for their own block's facts; the
`architecture` hub (arch.yml + the compiler guide + STATUS) tends to go stale
when a block changes. This runs Claude over both, and opens / updates / closes a
single GitHub issue with any concrete divergences. Runs in CI (nightly + manual).

Env: ANTHROPIC_API_KEY (Claude), GITHUB_TOKEN + GH_REPO (issue via `gh`),
     DRIFT_MODEL (optional, default claude-opus-4-8).
"""
from __future__ import annotations
import glob, os, subprocess, sys
import anthropic

ISSUE_TITLE = "🔄 Architecture drift check"

# block repos cloned as siblings under block_repos/ by the workflow
BLOCK_REPOS = {
    "ACU / block 1 — attention-compute-unit": "block_repos/attention-compute-unit",
    "KVCE / block 2 — kv-cache-engine": "block_repos/kv-cache-engine",
    "TIU / block 3 — token-importance-unit": "block_repos/token-importance-unit",
}
ARCH_FILES = ["arch.yml", "docs/compiler_programming_guide.md", "STATUS.md",
              "dataflow_walkthrough.md"]


def read(path: str, limit: int = 45000) -> str:
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            return f.read()[:limit]
    except FileNotFoundError:
        return ""


def gather_block(repo_dir: str) -> str:
    parts = []
    files = [f"{repo_dir}/README.md"] + sorted(glob.glob(f"{repo_dir}/docs/isa/*_isa.md"))
    for p in files:
        txt = read(p, 22000)
        if txt:
            parts.append(f"### FILE {p}\n{txt}")
    return "\n\n".join(parts) or "(no readable files found)"


PROMPT = """You audit whether the LonghornSilicon ARCHITECTURE repo (the hub: arch.yml, the \
compiler programming guide, STATUS, the dataflow walkthrough) is STALE relative to the \
per-block repos. The per-block repos are the SOURCE OF TRUTH for their own block's facts.

Report ONLY concrete, factual divergences that would mislead a reader: codec / tier names \
(e.g. ChannelQuant, CQ-8/CQ-4/CQ-4+), key parameters (group G, outlier k, N_SLOTS, \
SCORE_WIDTH, head dims, accumulator widths), sign-off / accuracy numbers, per-block build \
status, the MatE precision path (INT8×INT4 vs FP16 escape), and interface / ISA facts \
(register maps, op semantics, versions). IGNORE wording, tone, formatting, ordering, and \
roadmap phrasing.

For each divergence, give three lines:
  - BLOCK FACT: <the current fact from the block repo, cite the file>
  - HUB SAYS:   <the stale architecture claim, cite the file + what it says>
  - FIX:        <one-line suggested edit to the architecture repo>

If the architecture hub is consistent with every block repo, output EXACTLY this token and \
nothing else: NO_DRIFT

=== SOURCE OF TRUTH (block repos) ===
{src}

=== ARCHITECTURE HUB (may be stale) ===
{arch}
"""


def run_claude() -> str:
    src = "\n\n".join(f"## SOURCE OF TRUTH — {label}\n\n{gather_block(d)}"
                      for label, d in BLOCK_REPOS.items())
    arch = "\n\n".join(f"### FILE {p}\n{read(p)}" for p in ARCH_FILES)
    client = anthropic.Anthropic()
    with client.messages.stream(
        model=os.environ.get("DRIFT_MODEL", "claude-opus-4-8"),
        max_tokens=8000,
        output_config={"effort": "medium"},
        messages=[{"role": "user", "content": PROMPT.format(src=src, arch=arch)}],
    ) as stream:
        msg = stream.get_final_message()
    return "".join(b.text for b in msg.content if b.type == "text").strip()


def gh(*args: str) -> str:
    return subprocess.run(["gh", *args], capture_output=True, text=True).stdout.strip()


def find_open_issue() -> str | None:
    out = gh("issue", "list", "--state", "open", "--search", ISSUE_TITLE,
             "--json", "number,title", "--jq",
             f'.[] | select(.title=="{ISSUE_TITLE}") | .number')
    return out.splitlines()[0] if out else None


def main() -> int:
    report = run_claude()
    drift = report != "NO_DRIFT" and "NO_DRIFT" not in report.splitlines()[:1]
    existing = find_open_issue()
    body = (f"_Automated architecture drift check — the per-block repos are the source of "
            f"truth; this flags where the hub (arch.yml / compiler guide / STATUS) lags._\n\n"
            f"{report}\n\n---\n<sub>Generated by `.github/scripts/drift_check.py`. "
            f"Close once reconciled; it reopens/updates on the next run if drift persists.</sub>")

    if not drift:
        print("NO_DRIFT — architecture hub is consistent with the block repos.")
        if existing:
            gh("issue", "comment", existing, "--body",
               "✅ Latest drift check found no divergences — closing.")
            gh("issue", "close", existing)
        return 0

    print("DRIFT DETECTED:\n" + report)
    if existing:
        gh("issue", "comment", existing, "--body", "🔁 Re-checked; drift still present:\n\n" + body)
    else:
        gh("issue", "create", "--title", ISSUE_TITLE, "--body", body,
           "--label", "architecture-drift")
    return 0


if __name__ == "__main__":
    sys.exit(main())
